### ISSUE TITLE
pelitagame hangs when player throws an exception

### ISSUE THREAD

**Issue by keszybz** [ASPP/pelita#175]
Visible because of #162, but still valid on its own: it should not be possible to hang pelitagame with player code.
Adding this here to remember about it. This might be a linux-only problem, so I'll try to have a look at it.

% ./pelitagame --timeout 0.0001
Choosing NQRandomPlayer for random player
Choosing BasicDefensePlayer for random player
Choosing BasicDefensePlayer for random player
Choosing BasicDefensePlayer for random player
Using factory 'random' -> 'The NQRandomPlayers' (left)
Using factory 'random' -> 'The BasicDefensePlayers' (right)
tcp://localhost:50011 <zmq.core.socket.Socket object at 0x1142bf0> 18099184
Timeout #1 for team 0 (bot index 0).
Timeout #1 for team 1 (bot index 1).
Timeout #2 for team 0 (bot index 2).
Timeout #2 for team 1 (bot index 3).
Timeout #3 for team 0 (bot index 0).
Timeout #3 for team 1 (bot index 1).
Timeout #4 for team 0 (bot index 2).
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(_self._args, *_self._kwargs)
  File "/home/zbyszek/python/pelita/pelita/simplesetup.py", line 469, in run
    self._loop()
  File "/home/zbyszek/python/pelita/pelita/simplesetup.py", line 489, in _loop
    retval = getattr(self, action)(*_data)
  File "/home/zbyszek/python/pelita/pelita/simplesetup.py", line 499, in get_move
    return self.team.get_move(_args, *_kwargs)
  File "/home/zbyszek/python/pelita/pelita/player.py", line 80, in get_move
    return self._bot_players[bot_id]._get_move(universe, game_state)
  File "/home/zbyszek/python/pelita/pelita/player.py", line 163, in _get_move
    move = self.get_move()
  File "/home/zbyszek/python/pelita/pelita/player.py", line 687, in get_move
    return diff_pos(self.current_pos, self.path.pop())
  File "/home/zbyszek/python/pelita/pelita/datamodel.py", line 81, in diff_pos
    raise ValueError('%r is not adjacent to %r' % (initial, target))
ValueError: (1, 13) is not adjacent to (3, 14)
Timeout #4 for team 1 (bot index 3).
Team 0 (bot index 0) disconnected. Team disqualified.
Timeout #5 for team 1 (bot index 1). Team disqualified.
Team 0 (bot index 2) disconnected. Team disqualified.
Timeout #6 for team 1 (bot index 3).
Finished. u'The BasicDefensePlayers' won over u'The NQRandomPlayers'. (0:0)
Traceback (most recent call last):
  File "./pelitagame", line 457, in <module>
    run_game()
  File "./pelitagame", line 448, in run_game
    server.exit_teams()
  File "/home/zbyszek/python/pelita/pelita/simplesetup.py", line 348, in exit_teams
    team_player._exit()
  File "/home/zbyszek/python/pelita/pelita/simplesetup.py", line 216, in _exit
    self.zmqconnection.send("exit", {})
  File "/home/zbyszek/python/pelita/pelita/simplesetup.py", line 118, in send
    raise DeadConnection()
pelita.messaging.actor.DeadConnection
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(_targs, *_kargs)
  File "/usr/lib/python2.7/multiprocessing/util.py", line 295, in _exit_function
    p.join()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 148, in wait
    return self.poll(0)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 133, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(_targs, **kargs)
  File "/usr/lib/python2.7/multiprocessing/util.py", line 295, in _exit_function
    p.join()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 148, in wait
    return self.poll(0)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 133, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt

**Comment by otizonaizit** [comment]
This is fixed already.
