### ISSUE TITLE
Rewrite pelita.utils.create_layout to reuse the parser in layout.py

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#615]
This means, adding a new feature to parse_layout so that it can understand layouts of the type

    """
    ##########
    #01 .. EE#
    ##########
    """

Additionally, we will want to have a way to convert layouts of the type

    """
    ##########
    #02 .. 31#
    ##########
    """

to the version mentioned above.

**Comment by otizonaizit** [comment]
this should be easily doable by adding a `is_blue` flag to the layout string parsing function. Then its just:

```python
team = 0 if is_blue else 1
bot_idx = turn // 2
```
where `turn` is the number and you use the `bot_idx` only for the right team and the other bots get `E`. The round-trip can not work though, but that's expected, right?

**Comment by Debilski** [comment]
Yeah, this is the easy part. Adapting the parser in layout.py to also accept the layouts that contain `E` and then reshuffle the indexes is a little trickier. (Well, it is tricky to make it maintainable at least.)

**Comment by otizonaizit** [comment]
Right now the layout conversion in `team.py` does funny, and wrong, things. For example create this bot:

```python
TEAM_NAME='Stops'

def move(bot, state):
    print(bot)
    raise Exception
```

and run it with:

```pelita demo01_stopping.py newbot.py```

It will print the enemy bots in funny places. It works correctly if `newbot.py` plays on the left...

**Comment by Debilski** [comment]
Example please. Cannot reproduce.

**Comment by otizonaizit** [comment]
So. Put the following in `removeme.py`:
```python
TEAM_NAME='Stops'

def move(bot, state):
    print(bot)
    raise Exception
    return bot.position, state
```

then run a game from the `pelita_template` repo with:
```pelita --seed 1 --rounds 1 demo01_stopping.py /tmp/removeme.py```

This is the output I get, where the `E`s are not where they should (i.e. in the bottom left):
```
Using layout 'layout_normal_without_dead_ends_018'
ᗧ blue team 'demo01_stopping.py' -> 'StoppingBots'
ᗧ red team '/tmp/removeme.py' -> 'Stops'
StoppingBots vs Stops (you).
Playing on red side. Current turn: 0. Round: 1, score: 0:0. timeouts: 0:0
################################
#     .   .  ..## .     #  #   #
#..    .    .     ### #.#  # # #
#.#####.#.# # .    #  # #  #   #
# .#      # #. ##..#  # #    ###
## #.# .. # #      #   .#. .   #
#  #    .  .#      #  . ### ## #
#  ## ##  #  . ## .###        .#
#.        ###. ## .  #  ## ##  #
# ## ### .  #      #.  .    #  #
#   . .#.   #      # # .. #.# ##
###    # #  #..## .# #      #. #
#   #  # #  #    . # #.#.#####.#
# # #  #.# ###     .    .    ..#
#   #  #     . ##..  .   .     #
################################

################################
#              ##       #  #  1#
#                 ### # #  # #0#
# ##### # # #      #  # #  #   #
#  #      # #  ##  #  # #    ###
## # #    # #      #    #      #
#  #        #      #    ### ## #
#  ## ##  #    ##  ###         #
#         ###  ##    #  ## ##  #
#E## ###    #      #        #  #
#      #    #      # #    # # ##
###    # #  #  ##  # #      #  #
#   #E # #  #      # # # ##### #
# # #  # # ###                 #
#   #  #       ##              #
################################


Traceback (most recent call last):
  File "/home/tiziano/git/pelita/pelita/player/team.py", line 124, in get_move
    res = self._team_move(team[me._bot_turn], self._state)
  File "/tmp/removeme.py", line 5, in move
    raise Exception
Exception
ᗧ red team, bot 0: FatalException: Exception in client (Exception):
Finished. 'StoppingBots' won over 'Stops'. (0:0)
```

Even if you flip the order of the teams, the position of the enemies is wrong:
```
pelita --seed 1 --rounds 1 /tmp/removeme.py  demo01_stopping.py
Using layout 'layout_normal_without_dead_ends_018'
ᗧ red team 'demo01_stopping.py' -> 'StoppingBots'
ᗧ blue team '/tmp/removeme.py' -> 'Stops'
Stops (you) vs StoppingBots.
Playing on blue side. Current turn: 0. Round: 1, score: 0:0. timeouts: 0:0
################################
#     .   .  ..## .     #  #   #
#..    .    .     ### #.#  # # #
#.#####.#.# # .    #  # #  #   #
# .#      # #. ##..#  # #    ###
## #.# .. # #      #   .#. .   #
#  #    .  .#      #  . ### ## #
#  ## ##  #  . ## .###        .#
#.        ###. ## .  #  ## ##  #
# ## ### .  #      #.  .    #  #
#   . .#.   #      # # .. #.# ##
###    # #  #..## .# #      #. #
#   #  # #  #    . # #.#.#####.#
# # #  #.# ###     .    .    ..#
#   #  #     . ##..  .   .     #
################################

################################
#              ##       # E#   #
#                 ### # #  #E# #
# ##### # # #      #  # #  #   #
#  #      # #  ##  #  # #    ###
## # #    # #      #    #      #
#  #        #      #    ### ## #
#  ## ##  #    ##  ###         #
#         ###  ##    #  ## ##  #
# ## ###    #      #        #  #
#      #    #      # #    # # ##
###    # #  #  ##  # #      #  #
#   #  # #  #      # # # ##### #
#0# #  # # ###                 #
#1  #  #       ##              #
################################


Traceback (most recent call last):
  File "/home/tiziano/git/pelita/pelita/player/team.py", line 124, in get_move
    res = self._team_move(team[me._bot_turn], self._state)
  File "/tmp/removeme.py", line 5, in move
    raise Exception
Exception
ᗧ blue team, bot 0: FatalException: Exception in client (Exception):
Finished. 'StoppingBots' won over 'Stops'. (0:0)
```

Now that I look at it, it seems like the layout is not even a legal layout (not symmetric?)... hmmm, I am confused now...

**Comment by Debilski** [comment]
Well, sure, they are both noisy.

**Comment by otizonaizit** [comment]
Ahh, right! I forgot about that ;)

**Comment by Debilski** [comment]
Yeah, we should print that info as well (or mark the noisy enemies in a different style?)
