### ISSUE TITLE
crash in tk

### ISSUE THREAD

**Issue by keszybz** [ASPP/pelita#693]
```console
$ PYTHONPATH=../pelita python3 -m pelita.scripts.pelita_main demo01_stopping.py demo02_random.py    
Replay this game with --seed 6320038136106717129
Using layout 'normal_097'
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/usr/lib64/python3.7/tkinter/__init__.py", line 749, in callit
    func(*args)
  File "/home/zbyszek/pythonschool/pelita/pelita/ui/tk_viewer.py", line 143, in read_queue
    self.app.observe(game_state)
  File "/home/zbyszek/pythonschool/pelita/pelita/ui/tk_canvas.py", line 765, in observe
    self.update(game_state)
  File "/home/zbyszek/pythonschool/pelita/pelita/ui/tk_canvas.py", line 395, in update
    self.draw_universe(game_state)
  File "/home/zbyszek/pythonschool/pelita/pelita/ui/tk_canvas.py", line 422, in draw_universe
    self.draw_background()
  File "/home/zbyszek/pythonschool/pelita/pelita/ui/tk_canvas.py", line 492, in draw_background
    self.ui.game_canvas.create_line(x_orig, y_top, x_orig, y_bottom, width=scale, fill=color, tag="background")
  File "/usr/lib64/python3.7/tkinter/__init__.py", line 2492, in create_line
    return self._create('line', args, kw)
  File "/usr/lib64/python3.7/tkinter/__init__.py", line 2480, in _create
    *(args + self._options(cnf, kw))))
_tkinter.TclError: bad screen distance "-0.0625"
ᗧ blue team 'demo01_stopping.py' -> 'StoppingBots'
ᗧ red team 'demo02_random.py' -> 'RandomBots'
```

Happened only once. I cannot reproduce it again, even with `--seed`.

**Comment by Debilski** [comment]
Has been reported by a student as well and happened to me during the test run of the tournament.
